# Generated by Django 5.2.3 on 2025-06-25 19:38

from django.db import migrations

def add_articlestatus(apps, schema_editor):
    Articlestatus = apps.get_model("libtekin256", "Articlestatus")
    Articlestatus.objects.create(
        name="To Be Received",
        orderpos=7,
        show=1,
    )
    Articlestatus.objects.create(
        name="Available",
        orderpos=1,
        show=1,
    )
    Articlestatus.objects.create(
        name="Assigned",
        orderpos=2,
        show=1,
    )
    Articlestatus.objects.create(
        name="In Repair",
        orderpos=3,
        show=1,
    )
    Articlestatus.objects.create(
        name="Out of Service",
        orderpos=8,
        show=1,
    )
    Articlestatus.objects.create(
        name="Removed from Inventory",
        orderpos=9,
        show=1,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('libtekin256', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_articlestatus)
    ]
