# Generated by Django 5.2.3 on 2025-07-08 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin256', '0002_auto_20250625_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='The full name of this location', max_length=80, verbose_name='name')),
                ('abbreviation', models.CharField(blank=True, help_text='An abbreviation of the name', max_length=10, verbose_name='abbreviation')),
            ],
        ),
        migrations.AlterModelOptions(
            name='articlenotesubject',
            options={'ordering': ('last_used',)},
        ),
        migrations.AddField(
            model_name='article',
            name='home_location',
            field=models.ForeignKey(blank=True, help_text='The home location of the article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_articles', to='libtekin256.location'),
        ),
        migrations.AddField(
            model_name='articlesnap',
            name='home_location',
            field=models.ForeignKey(blank=True, help_text="The article's home location", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_location_history', to='libtekin256.location'),
        ),
    ]
