# Generated by Django 5.2.3 on 2025-07-17 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin256', '0003_location_alter_articlenotesubject_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleCategory',
            new_name='Role',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='articlesnap',
            old_name='category',
            new_name='role'
        ),
        migrations.AlterField(
            model_name='article',
            name='role',
            field=models.ForeignKey(blank=True, help_text='The role of this article', null=True, on_delete=django.db.models.deletion.SET_NULL, to='libtekin256.role'),
        ),
        migrations.AlterField(
            model_name='articlesnap',
            name='role',
            field=models.ForeignKey(blank=True, help_text='The role of this article', null=True, on_delete=django.db.models.deletion.SET_NULL, to='libtekin256.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='The name of this role', max_length=60, verbose_name='name'),
        ),
    ]
