# Generated by Django 5.2.5 on 2025-09-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin256', '0004_role_remove_article_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleNoteSubject',
            new_name='ArticleNoteStandardSubject',
        ),
        migrations.RemoveField(
            model_name='articlenote',
            name='subject',
        ),
        migrations.AddField(
            model_name='articlenote',
            name='standard_subject',
            field=models.ForeignKey(blank=True, help_text='The subject of this note', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='libtekin256.articlenotestandardsubject', verbose_name='standard subject'),
        ),
    ]
