# Generated by Django 5.2.5 on 2025-09-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin256', '0004_role_remove_article_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleNoteSubject',
            new_name='ArticleNoteStandardSubject',
        ),
        migrations.RenameField(
            model_name='articlenote',
            old_name='subject',
            new_name='standard_subject',
        ),
    ]
