# Generated by Django 5.2.5 on 2025-09-05 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin256', '0005_rename_articlenotesubject_articlenotestandardsubject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlenote',
            name='individual_subject',
            field=models.CharField(blank=True, help_text='The individual subject of this note. Should be filled in if standard subject is not used', max_length=255, verbose_name='individual subject'),
        ),
        migrations.AlterField(
            model_name='articlenote',
            name='standard_subject',
            field=models.ForeignKey(blank=True, help_text='The standard subject of this note, if a standard subject is used', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='libtekin256.articlenotestandardsubject', verbose_name='standard subject'),
        ),
    ]
