# Generated by Django 6.0.3 on 2026-03-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin256', '0006_articlenote_individual_subject_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleNoteStandardSubject',
            new_name='ArticleNoteSubject',
        ),
        migrations.RenameField(
            model_name='articlenote',
            old_name='standard_subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='articlenote',
            old_name='individual_subject',
            new_name='summary',
        ),
    ]
