# Generated by Django 6.0.3 on 2026-03-26 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin256', '0007_rename_articlenotestandardsubject_articlenotesubject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlenote',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='The standard subject of this note, if a standard subject is used', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='libtekin256.articlenotesubject', verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='articlenote',
            name='summary',
            field=models.CharField(blank=True, help_text='A summary - like a subject line but with more detail than the available subjects in the drop down list', max_length=255, verbose_name='summary'),
        ),
    ]
