# Generated by Django 6.0.3 on 2026-04-03 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin256', '0008_alter_articlenote_subject_alter_articlenote_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlenote',
            options={'ordering': ('-when', '-updated_at')},
        ),
        migrations.AddField(
            model_name='articlenote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date this note was upated.  Used for sorting', verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='articlenote',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='If this note is both current and important - for examples: if the article is under watch due to problems, has a special condition or feature, is on loan, etc..', verbose_name='pinned'),
        ),
        migrations.AlterField(
            model_name='articlenote',
            name='when',
            field=models.DateField(default=datetime.date.today, help_text='The date that the event occured or the action was taken if appliable, or the date that this note was made', verbose_name='date'),
        ),
    ]
