# Generated by Django 6.0.3 on 2026-04-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin256', '0009_alter_articlenote_options_articlenote_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlenotesubject',
            options={'ordering': ('-last_used',)},
        ),
    ]
