# Generated by Django 6.0.3 on 2026-04-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtekin256', '0010_alter_articlenotesubject_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlenote',
            name='summary',
        ),
        migrations.AddField(
            model_name='articlenote',
            name='resolution',
            field=models.CharField(blank=True, help_text='For problems - a description of the resolution', max_length=255, verbose_name='resolution'),
        ),
        migrations.AlterField(
            model_name='articlenote',
            name='description',
            field=models.TextField(blank=True, help_text='The description, if needed, and updates not including the resolution', max_length=255, verbose_name='description/updates'),
        ),
        migrations.AlterField(
            model_name='articlenote',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='If this note is both current and important (unpin an problem when the problem is revolved) - for examples: if the article is under watch due to problems, has a special condition or feature, is on loan, etc..', verbose_name='pinned'),
        ),
    ]
